"""
Django settings for SchoolApp project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from django.core.management.utils import get_random_secret_key
import dotenv

# Load environment variables from .env file if it exists
dotenv.load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Use environment variable for SECRET_KEY or generate a random one
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", get_random_secret_key())

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "False").lower() == "true"

# Restrict allowed hosts - remove wildcard "*" in production
ALLOWED_HOSTS = os.environ.get(

    "ALLOWED_HOSTS", "localhost,127.0.0.1,192.168.5.1,localhost:8000,127.0.0.1:8000,testserver"

).split(",")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "shs_system",
    "super_admin",  # New app for super admin functionality
    "widget_tweaks",
    "crispy_forms",
    "crispy_bootstrap5",  # Add this for Bootstrap 5 support
    "social_django",
    "django.contrib.sessions.backends.cache",  # For better session handling
    # "django_secure_auth",  # Removed non-existent package
    "axes",  # Added django-axes for login attempt tracking
]
CRISPY_TEMPLATE_PACK = "bootstrap5"  # or 'bootstrap5' if you're using Bootstrap 5
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"  # Allow Bootstrap 5 template pack

# Session security settings
SESSION_COOKIE_AGE = int(
    os.environ.get("SESSION_COOKIE_AGE", "36000000")
)  # 1 hour default
SESSION_SAVE_EVERY_REQUEST = True  # Update the session expiry time after each request
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Sessions expire when browser closes
SESSION_COOKIE_SECURE = not DEBUG  # Use secure cookies in production
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_SAMESITE = "Lax"  # Restrict cookie sending to same-site requests

# Temporarily disable CSRF for testing
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False
CSRF_TRUSTED_ORIGINS = os.environ.get(
    "CSRF_TRUSTED_ORIGINS",
    "http://localhost:8000,http://127.0.0.1:8000,http://192.168.1.100:8000,http://192.168.1.101:8000,http://192.168.5.1:8000",
).split(",")
DATA_UPLOAD_MAX_NUMBER_FIELDS = 50000  # Increased for bulk operations
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB for large CSV files
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB for file uploads

# Bulk operation settings
BULK_OPERATION_BATCH_SIZE = 100  # Default batch size for bulk operations
BULK_DELETE_BATCH_SIZE = 50  # Smaller batch size for deletions
BULK_OPERATION_TIMEOUT = 300  # 5 minutes timeout for bulk operations
# Security middleware and settings
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",  # Removed duplicate
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "super_admin.middleware.SchoolMiddleware",  # Add this before the RoleBasedAccessMiddleware
    "super_admin.middleware.ImpersonationMiddleware",  # Add the impersonation middleware
    "shs_system.middleware.RoleBasedAccessMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "social_django.middleware.SocialAuthExceptionMiddleware",
    "axes.middleware.AxesMiddleware",  # Django-axes middleware for login security
    "csp.middleware.CSPMiddleware",  # Content Security Policy
]

# Django-axes configuration - Relaxed for development/testing
AXES_FAILURE_LIMIT = 10  # Increased from 5 to 10 attempts
AXES_COOLOFF_TIME = 0.1  # Reduced to 6 minutes (0.1 hours) for development
AXES_LOCKOUT_TEMPLATE = (
    "account/lockout.html"  # Optional template to show when locked out
)
AXES_LOCKOUT_URL = "/locked-out/"  # Optional URL to redirect to when locked out
AXES_LOCKOUT_PARAMETERS = [
    "ip_address"
]  # Only lock by IP, not user agent for easier testing
AXES_DISABLE_ACCESS_LOG = True  # Disable access logging to reduce noise

# Security headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_SSL_REDIRECT = False  # Disable SSL redirect for local development

# Content Security Policy (Edge compatible)
CSP_DEFAULT_SRC = (
    "'self'",
    "'unsafe-inline'",
    "'unsafe-eval'",
    "data:",
    "blob:",
    "http:",
    "https:",
)
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https:")
CSP_SCRIPT_SRC = (
    "'self'",
    "'unsafe-inline'",
    "'unsafe-eval'",
    "https:",
)
CSP_IMG_SRC = ("'self'", "data:", "https:")
CSP_FONT_SRC = ("'self'", "data:", "https:")
CSP_CONNECT_SRC = ("'self'", "https:")

# Multi-tenancy settings
MULTI_TENANT_SUBDOMAIN_ROUTING = True  # Enable subdomain-based routing
MULTI_TENANT_PATH_ROUTING = True  # Enable path-based routing for development
DEVELOPMENT_MODE = os.environ.get("DEVELOPMENT_MODE", "False").lower() == "true"
STRICT_TENANT_ROUTING = False  # If True, non-existent school slugs will 404
SUPER_ADMIN_SUBDOMAIN = "superadmin"  # Subdomain for super admin site
SUPER_ADMIN_PATH = (
    "super-admin"  # Path prefix for super admin site (if using path routing)
)

USE_I18N = True
ROOT_URLCONF = "SchoolApp.urls"
LOGIN_URL = "/school/"  # Redirects unauthenticated users to the login page
LOGIN_REDIRECT_URL = "/dashboard/"  # Redirects after successful login

LOGOUT_REDIRECT_URL = "/"  # Redirects logged-out users to the landing page


# Password and account security
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "shs_system.context_processors.sweet_alert",
                "shs_system.context_processors.session_expiry",
                "shs_system.context_processors.current_academic_context",  # Current academic year and term context
                "shs_system.context_processors.teacher_monitoring_summary",
                "shs_system.context_processors.school_context",  # Our new school context processor
                "super_admin.context_processors.school_context",  # School context processor
            ],
            "string_if_invalid": "",  # Disable potentially dangerous features in templates
        },
    },
]

WSGI_APPLICATION = "SchoolApp.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME", "multi_sis_database"),
        "USER": os.environ.get("DB_USER", "postgres"),
        "PASSWORD": os.environ.get("DB_PASSWORD", ""),
        "HOST": os.environ.get("DB_HOST", "localhost"),
        "PORT": os.environ.get("DB_PORT", "5432"),
        "OPTIONS": {
            "connect_timeout": 60,
        },
        # Optimized settings for bulk operations
        "ATOMIC_REQUESTS": False,  # Disabled for better control over transactions in bulk operations
        "CONN_MAX_AGE": 300,  # Longer persistent connections for bulk operations
        "CONN_HEALTH_CHECKS": True,  # Check connection health before use
    }
}

# Cache settings for better performance and security
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    }
}

# For handling time zones correctly
USE_TZ = True

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        "OPTIONS": {
            "user_attributes": ["username", "email", "first_name", "last_name"],
            "max_similarity": 0.7,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 10,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Account lockout settings
ACCOUNT_LOCKOUT_ATTEMPTS = 5  # Lock after 5 failed attempts
ACCOUNT_LOCKOUT_TIME = 300  # Lock for 5 minutes (in seconds)

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Media files (Uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# Backup and Restore Settings
BACKUP_DIR = os.path.join(BASE_DIR, "backups")
BACKUP_RETENTION_DAYS = 30  # Keep backups for 30 days by default
BACKUP_MAX_SIZE_MB = 1000  # Maximum backup size in MB
BACKUP_COMPRESSION_LEVEL = 6  # ZIP compression level (1-9)


# File upload security
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5 MB
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755
FILE_UPLOAD_HANDLERS = [
    "django.core.files.uploadhandler.MemoryFileUploadHandler",
    "django.core.files.uploadhandler.TemporaryFileUploadHandler",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "shs_system.User"  # Replace 'shs_system' with the name of your app

# Site URL for email links
SITE_URL = os.environ.get("SITE_URL", "http://localhost:8000")

# Authentication backends
AUTHENTICATION_BACKENDS = (
    "axes.backends.AxesStandaloneBackend",  # Django-axes authentication backend
    "social_core.backends.google.GoogleOAuth2",  # Google OAuth2
    "django.contrib.auth.backends.ModelBackend",  # Django default
)

# Google OAuth2 settings - Move to environment variables
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.environ.get("SOCIAL_AUTH_GOOGLE_OAUTH2_KEY", "")
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.environ.get(
    "SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET", ""
)
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    "https://www.googleapis.com/auth/userinfo.email",
    "https://www.googleapis.com/auth/userinfo.profile",
    "https://www.googleapis.com/auth/gmail.send",  # For sending emails
]

# Social Auth settings
SOCIAL_AUTH_LOGIN_REDIRECT_URL = "/dashboard/"
SOCIAL_AUTH_LOGIN_ERROR_URL = "/login/"
SOCIAL_AUTH_URL_NAMESPACE = "social"
SOCIAL_AUTH_PIPELINE = (
    "social_core.pipeline.social_auth.social_details",
    "social_core.pipeline.social_auth.social_uid",
    "social_core.pipeline.social_auth.social_user",
    "social_core.pipeline.user.get_username",
    "social_core.pipeline.social_auth.associate_by_email",
    "social_core.pipeline.user.create_user",
    "social_core.pipeline.social_auth.associate_user",
    "social_core.pipeline.social_auth.load_extra_data",
    "social_core.pipeline.user.user_details",
    "shs_system.pipeline.save_profile",  # Custom pipeline function to save additional user data
    "shs_system.pipeline.set_default_role",  # Custom pipeline function to set default role for new users
)

# Rate limiting to prevent brute force attacks
RATELIMIT_ENABLE = True
RATELIMIT_USE_CACHE = "default"
RATELIMIT_VIEW = "shs_system.views.ratelimited_error"
RATELIMIT_RATE = {
    "login": "5/m",  # 5 login attempts per minute
    "password_reset": "3/h",  # 3 password reset attempts per hour
}

# Email Configuration with SSL
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "465"))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "False").lower() == "true"
EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "True").lower() == "true"
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)

# Option to disable email sending completely
# Set to True to disable all email sending throughout the application
DISABLE_EMAIL_SENDING = (
    os.environ.get("DISABLE_EMAIL_SENDING", "False").lower() == "true"
)

# Custom test runner configuration
TEST_RUNNER = "shs_system.tests.test_runner.DetailedTestRunner"

# Debug settings
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
    },
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "filters": ["require_debug_true"],
        },
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "logs/debug.log"),
            "maxBytes": 10485760,  # 10MB
            "backupCount": 10,
            "formatter": "verbose",
        },
        "mail_admins": {
            "level": "ERROR",
            "class": "django.utils.log.AdminEmailHandler",
            "filters": ["require_debug_false"],
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": os.environ.get("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": True,
        },
        "django.security": {
            "handlers": ["console", "file", "mail_admins"],
            "level": "INFO",
            "propagate": False,
        },
        "super_admin.middleware": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "shs_system.teacher_monitoring": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "super_admin.views": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "django.utils.smtp": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "django.core.mail": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "axes": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Create logs directory if it doesn't exist
os.makedirs(os.path.join(BASE_DIR, "logs"), exist_ok=True)

# Security auditing
SECURITY_AUDIT_ENABLED = True
SECURITY_AUDIT_LOG_FILE = os.path.join(BASE_DIR, "logs/security_audit.log")

# Set admins for error emails
ADMINS = [
    ("Admin", os.environ.get("ADMIN_EMAIL", "admin@example.com")),
]

# Secure file uploads
SECURE_FILE_UPLOADS = True
ALLOWED_UPLOAD_EXTENSIONS = [
    ".jpg",
    ".jpeg",
    ".png",
    ".pdf",
    ".doc",
    ".docx",
    ".xls",
    ".xlsx",
    ".txt",
]
MAX_UPLOAD_SIZE = 5242880  # 5 MB


# Backup and Restore Configuration
# Use local drive path for backups (accessible from Docker containers)
BACKUP_DIR = os.environ.get("BACKUP_DIR", r"C:\backups")
# Ensure backup directory exists
os.makedirs(BACKUP_DIR, exist_ok=True)

