# Generated by Django 5.0.14 on 2025-12-05 06:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("shs_system", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annually", "Annually"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("max_students", models.PositiveIntegerField(default=500)),
                ("max_teachers", models.PositiveIntegerField(default=50)),
                ("max_storage_gb", models.PositiveIntegerField(default=5)),
                ("features", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SuperAdminSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="SchoolApp Platform", max_length=100),
                ),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "support_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("default_trial_days", models.PositiveIntegerField(default=30)),
                ("allow_new_registrations", models.BooleanField(default=True)),
                ("terms_and_conditions", models.TextField(blank=True, null=True)),
                ("privacy_policy", models.TextField(blank=True, null=True)),
                (
                    "platform_fee_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("is_maintenance_mode", models.BooleanField(default=False)),
                ("maintenance_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Super Admin Settings",
                "verbose_name_plural": "Super Admin Settings",
            },
        ),
        migrations.CreateModel(
            name="SystemEmailConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="System Email", max_length=100)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("smtp", "SMTP Server"),
                            ("oauth", "OAuth2 (Google)"),
                            ("api", "Email API Service"),
                        ],
                        default="oauth",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("smtp_host", models.CharField(blank=True, max_length=255, null=True)),
                ("smtp_port", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "smtp_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "smtp_password",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("smtp_use_tls", models.BooleanField(default=False)),
                ("smtp_use_ssl", models.BooleanField(default=True)),
                (
                    "oauth_provider",
                    models.CharField(blank=True, default="google", max_length=50),
                ),
                ("client_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "client_secret",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("access_token", models.TextField(blank=True, null=True)),
                (
                    "token_uri",
                    models.CharField(
                        blank=True,
                        default="https://oauth2.googleapis.com/token",
                        max_length=255,
                    ),
                ),
                ("scopes", models.JSONField(default=list)),
                ("from_email", models.EmailField(max_length=254)),
                ("from_name", models.CharField(blank=True, max_length=100, null=True)),
                ("reply_to", models.EmailField(blank=True, max_length=254, null=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "System Email Configuration",
                "verbose_name_plural": "System Email Configurations",
            },
        ),
        migrations.CreateModel(
            name="SchoolDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=255, unique=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("verification_token", models.UUIDField(default=uuid.uuid4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="shs_system.schoolinformation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("trial", "Trial"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("pending", "Pending"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField()),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subscription_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("auto_renew", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="super_admin.plan",
                    ),
                ),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="shs_system.schoolinformation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("payment_method", models.CharField(max_length=100)),
                ("transaction_id", models.CharField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("receipt_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="super_admin.subscription",
                    ),
                ),
            ],
        ),
    ]
