# Generated by Django 5.0.14 on 2026-02-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shs_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolinformation",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="school_image/"),
        ),
        migrations.AlterField(
            model_name="schoolinformation",
            name="school_stamp",
            field=models.ImageField(blank=True, null=True, upload_to="school_image/"),
        ),
    ]
