# Generated by Django 5.0.14 on 2026-02-25 04:41

import shs_system.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shs_system", "0003_update_upload_paths"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pictures/students/",
                validators=[shs_system.models.validate_image_size_150kb],
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pictures/teachers/",
                validators=[shs_system.models.validate_image_size_150kb],
            ),
        ),
    ]
